
import java.awt.Color;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Werner
 */
public class Scientific extends javax.swing.JFrame {
 DecimalFormat format = new DecimalFormat("#,###.00");
static int flag = 0;
    /**
     * Creates new form Scientific
     */
    public Scientific() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        outerPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        mainScreen = new javax.swing.JTextField();
        scientificPanel = new javax.swing.JPanel();
        openBraket = new javax.swing.JButton();
        closeBraket = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        onButton = new javax.swing.JRadioButton();
        offButton = new javax.swing.JRadioButton();
        keypadPanel = new javax.swing.JPanel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        comaButton = new javax.swing.JButton();
        pieButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        outerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));

        displayPanel.setBackground(new java.awt.Color(153, 255, 153));
        displayPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        mainScreen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mainScreen.setBorder(null);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScreen)
                .addContainerGap())
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        scientificPanel.setBackground(new java.awt.Color(153, 255, 153));
        scientificPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        openBraket.setText("(");
        openBraket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openBraketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openBraketMouseExited(evt);
            }
        });
        openBraket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBraketActionPerformed(evt);
            }
        });

        closeBraket.setText(")");
        closeBraket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBraketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBraketMouseExited(evt);
            }
        });
        closeBraket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBraketActionPerformed(evt);
            }
        });

        sinButton.setText("sin");
        sinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sinButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sinButtonMouseExited(evt);
            }
        });
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cosButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cosButtonMouseExited(evt);
            }
        });
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        tanButton.setText("tan");
        tanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tanButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tanButtonMouseExited(evt);
            }
        });
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });

        logButton.setText("log");
        logButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logButtonMouseExited(evt);
            }
        });
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        onButton.setBackground(new java.awt.Color(102, 102, 255));
        onButton.setText("ON");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });

        offButton.setBackground(new java.awt.Color(255, 51, 51));
        offButton.setText("OFF");
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scientificPanelLayout = new javax.swing.GroupLayout(scientificPanel);
        scientificPanel.setLayout(scientificPanelLayout);
        scientificPanelLayout.setHorizontalGroup(
            scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scientificPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openBraket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeBraket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        scientificPanelLayout.setVerticalGroup(
            scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scientificPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinButton)
                    .addComponent(cosButton)
                    .addComponent(onButton)
                    .addComponent(offButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scientificPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanButton)
                    .addComponent(closeBraket)
                    .addComponent(openBraket)
                    .addComponent(logButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        keypadPanel.setBackground(new java.awt.Color(153, 255, 153));
        keypadPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));

        oneButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        oneButton.setText("1");
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oneButtonMouseExited(evt);
            }
        });
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        twoButton.setText("2");
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                twoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twoButtonMouseExited(evt);
            }
        });
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        threeButton.setText("3");
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                threeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                threeButtonMouseExited(evt);
            }
        });
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        fourButton.setText("4");
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fourButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fourButtonMouseExited(evt);
            }
        });
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fiveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fiveButtonMouseExited(evt);
            }
        });
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        sixButton.setText("6");
        sixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sixButtonMouseExited(evt);
            }
        });
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sevenButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sevenButtonMouseExited(evt);
            }
        });
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        eightButton.setText("8");
        eightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eightButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eightButtonMouseExited(evt);
            }
        });
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        nineButton.setText("9");
        nineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nineButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nineButtonMouseExited(evt);
            }
        });
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zeroButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zeroButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                zeroButtonMousePressed(evt);
            }
        });
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        equalButton.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        equalButton.setText("=");
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equalButtonMouseExited(evt);
            }
        });
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        plusButton.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        plusButton.setText("+");
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusButtonMouseExited(evt);
            }
        });
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        minusButton.setText("-");
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minusButtonMouseExited(evt);
            }
        });
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        multiplyButton.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        multiplyButton.setText("x");
        multiplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplyButtonMouseExited(evt);
            }
        });
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        divideButton.setText("/");
        divideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divideButtonMouseExited(evt);
            }
        });
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Modern No. 20", 0, 10)); // NOI18N
        deleteButton.setText("D");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Modern No. 20", 0, 10)); // NOI18N
        cancelButton.setText("C");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        comaButton.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        comaButton.setText(".");
        comaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comaButtonMouseExited(evt);
            }
        });
        comaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaButtonActionPerformed(evt);
            }
        });

        pieButton.setFont(new java.awt.Font("Modern No. 20", 1, 10)); // NOI18N
        pieButton.setText("p");
        pieButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pieButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pieButtonMouseExited(evt);
            }
        });
        pieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keypadPanelLayout = new javax.swing.GroupLayout(keypadPanel);
        keypadPanel.setLayout(keypadPanelLayout);
        keypadPanelLayout.setHorizontalGroup(
            keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keypadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(fourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keypadPanelLayout.createSequentialGroup()
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(keypadPanelLayout.createSequentialGroup()
                                .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(keypadPanelLayout.createSequentialGroup()
                                        .addComponent(twoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(keypadPanelLayout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2))
                            .addGroup(keypadPanelLayout.createSequentialGroup()
                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(plusButton)))
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteButton)
                                .addComponent(multiplyButton))))
                    .addGroup(keypadPanelLayout.createSequentialGroup()
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        keypadPanelLayout.setVerticalGroup(
            keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(keypadPanelLayout.createSequentialGroup()
                .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keypadPanelLayout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(keypadPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addGap(8, 8, 8)
                .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comaButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, keypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout outerPanelLayout = new javax.swing.GroupLayout(outerPanel);
        outerPanel.setLayout(outerPanelLayout);
        outerPanelLayout.setHorizontalGroup(
            outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, outerPanelLayout.createSequentialGroup()
                        .addGroup(outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scientificPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keypadPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        outerPanelLayout.setVerticalGroup(
            outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scientificPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keypadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
         mainScreen.setText(mainScreen.getText()+"3");
    }//GEN-LAST:event_threeButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
    mainScreen.setText(mainScreen.getText()+" + ");  
    flag = 4;
    }//GEN-LAST:event_plusButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
      double s = Double.parseDouble(String.valueOf(mainScreen.getText()));
       s = Math.cos(s);
       mainScreen.setText(String.valueOf(s));
    }//GEN-LAST:event_cosButtonActionPerformed

    private void pieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieButtonActionPerformed
         mainScreen.setText(mainScreen.getText()+"3.14159");
         flag = 5;
    }//GEN-LAST:event_pieButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        mainScreen.setText(mainScreen.getText()+"1");
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
      mainScreen.setText(mainScreen.getText()+"2");
    }//GEN-LAST:event_twoButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
         mainScreen.setText(mainScreen.getText()+"4");
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
      mainScreen.setText(mainScreen.getText()+"5");
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        mainScreen.setText(mainScreen.getText()+"6");
    }//GEN-LAST:event_sixButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
       mainScreen.setText(mainScreen.getText()+"8");
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
      mainScreen.setText(mainScreen.getText()+"9");
    }//GEN-LAST:event_nineButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        mainScreen.setText(mainScreen.getText()+"0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
       mainScreen.setText(mainScreen.getText()+"7");
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
         mainScreen.setText("");
         flag =0; 
                
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void comaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaButtonActionPerformed
         mainScreen.setText(mainScreen.getText()+".");
    }//GEN-LAST:event_comaButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        mainScreen.setText(mainScreen.getText()+" * ");
        flag = 1;
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
     mainScreen.setText(mainScreen.getText()+ " - ");
     flag = 3;
    }//GEN-LAST:event_minusButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
         mainScreen.setText(mainScreen.getText()+" / ");
         flag = 2;
    }//GEN-LAST:event_divideButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
     if (mainScreen.getText().isEmpty() || mainScreen.getText().equals(ABORT)){
       
      equalButton.setAction(null);
     }else{
        mainScreen.setText(mainScreen.getText()+"  = ");
       String str = mainScreen.getText();
       String [] substr = str.split("\\s+");
       Float num1 = Float.parseFloat(substr[0]);
       Float num2 = Float.parseFloat(substr[2]);
      
       if(flag == 1){
           mainScreen.setText(mainScreen.getText()+" "+format.format(num1 * num2));
       }
        if(flag == 2){
           mainScreen.setText(mainScreen.getText()+" "+(num1 / num2));
       }
         if(flag == 3){
           mainScreen.setText(mainScreen.getText()+" "+(num1 - num2));
       }
          if(flag == 4){
           mainScreen.setText(mainScreen.getText()+" "+(num1 + num2));
       }
           if(flag == 5){
           mainScreen.setText(mainScreen.getText()+" "+( num1 * 3.14159 ));
       }
     }
    }//GEN-LAST:event_equalButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
     String deleteOne = null;
     if(mainScreen.getText().length()  >  0){
         StringBuilder strb =  new StringBuilder(mainScreen.getText());
         strb.deleteCharAt(mainScreen.getText().length() - 1);
         deleteOne = strb.toString();
         mainScreen.setText(deleteOne);
     }
     
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
       double s = Double.parseDouble(String.valueOf(mainScreen.getText()));
       s = Math.sin(s);
       mainScreen.setText(String.valueOf(s));
    }//GEN-LAST:event_sinButtonActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
        double s = Double.parseDouble(String.valueOf(mainScreen.getText()));
       s = Math.tan(s);
       mainScreen.setText(String.valueOf(s));
    }//GEN-LAST:event_tanButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
     double s = Double.parseDouble(String.valueOf(mainScreen.getText()));
       s = Math.log(s);
       mainScreen.setText(String.valueOf(s));
    }//GEN-LAST:event_logButtonActionPerformed

    private void openBraketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBraketActionPerformed
         mainScreen.setText(mainScreen.getText()+ " ( ");
    }//GEN-LAST:event_openBraketActionPerformed

    private void closeBraketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBraketActionPerformed
      mainScreen.setText(mainScreen.getText()+ " ) ");
    }//GEN-LAST:event_closeBraketActionPerformed

    private void oneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseEntered
        this.oneButton.setBackground(Color.GREEN);
    }//GEN-LAST:event_oneButtonMouseEntered

    private void oneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseExited
     this.oneButton.setBackground(Color.LIGHT_GRAY);   
    }//GEN-LAST:event_oneButtonMouseExited

    private void twoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseEntered
       this.twoButton.setBackground(Color.GREEN);
    }//GEN-LAST:event_twoButtonMouseEntered

    private void twoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseExited
       this.twoButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_twoButtonMouseExited

    private void threeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseEntered
      this.threeButton.setBackground(Color.GREEN);
    }//GEN-LAST:event_threeButtonMouseEntered

    private void threeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseExited
        this.threeButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_threeButtonMouseExited

    private void fourButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseEntered
      this.fourButton.setBackground(Color.green);  
    }//GEN-LAST:event_fourButtonMouseEntered

    private void fourButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseExited
     this.fourButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_fourButtonMouseExited

    private void fiveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseEntered
      this.fiveButton.setBackground(Color.green);
    }//GEN-LAST:event_fiveButtonMouseEntered

    private void fiveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseExited
      this.fiveButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_fiveButtonMouseExited

    private void sixButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseEntered
       this.sixButton.setBackground(Color.green);
    }//GEN-LAST:event_sixButtonMouseEntered

    private void sixButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseExited
       this.sixButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_sixButtonMouseExited

    private void sevenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseEntered
     this.sevenButton.setBackground(Color.green);
    }//GEN-LAST:event_sevenButtonMouseEntered

    private void sevenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseExited
      this.sevenButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_sevenButtonMouseExited

    private void eightButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseEntered
        this.eightButton.setBackground(Color.green);
    }//GEN-LAST:event_eightButtonMouseEntered

    private void eightButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseExited
      this.eightButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_eightButtonMouseExited

    private void nineButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseEntered
        this.nineButton.setBackground(Color.green);
    }//GEN-LAST:event_nineButtonMouseEntered

    private void nineButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseExited
      this.nineButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_nineButtonMouseExited

    private void zeroButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseEntered
    this.zeroButton.setBackground(Color.green);
    }//GEN-LAST:event_zeroButtonMouseEntered

    private void zeroButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroButtonMousePressed

    private void zeroButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseExited
    this.zeroButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_zeroButtonMouseExited

    private void comaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comaButtonMouseEntered
     this.comaButton.setBackground(Color.green);
    }//GEN-LAST:event_comaButtonMouseEntered

    private void comaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comaButtonMouseExited
         this.comaButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_comaButtonMouseExited

    private void pieButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieButtonMouseEntered
        this.pieButton.setBackground(Color.green);
    }//GEN-LAST:event_pieButtonMouseEntered

    private void pieButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieButtonMouseExited
         this.pieButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_pieButtonMouseExited

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
         this.cancelButton.setBackground(Color.green);
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited
      this.cancelButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_cancelButtonMouseExited

    private void plusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseEntered
     this.plusButton.setBackground(Color.green);
    }//GEN-LAST:event_plusButtonMouseEntered

    private void plusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseExited
      this.plusButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_plusButtonMouseExited

    private void divideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideButtonMouseEntered
      this.divideButton.setBackground(Color.green);
    }//GEN-LAST:event_divideButtonMouseEntered

    private void divideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideButtonMouseExited
    this.divideButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_divideButtonMouseExited

    private void equalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseEntered
     this.equalButton.setBackground(Color.green);
    }//GEN-LAST:event_equalButtonMouseEntered

    private void equalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseExited
    this.equalButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_equalButtonMouseExited

    private void minusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseEntered
     this.minusButton.setBackground(Color.green);   
    }//GEN-LAST:event_minusButtonMouseEntered

    private void minusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseExited
     this.minusButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_minusButtonMouseExited

    private void multiplyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyButtonMouseEntered
        this.multiplyButton.setBackground(Color.green);
    }//GEN-LAST:event_multiplyButtonMouseEntered

    private void multiplyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyButtonMouseExited
        this.multiplyButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_multiplyButtonMouseExited

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
     this.deleteButton.setBackground(Color.green);
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
       this.deleteButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_deleteButtonMouseExited

    private void sinButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinButtonMouseEntered
     this.sinButton.setBackground(Color.green);
    }//GEN-LAST:event_sinButtonMouseEntered

    private void sinButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinButtonMouseExited
       this.sinButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_sinButtonMouseExited

    private void cosButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosButtonMouseEntered
     this.cosButton.setBackground(Color.green);
    }//GEN-LAST:event_cosButtonMouseEntered

    private void cosButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosButtonMouseExited
      this.cosButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_cosButtonMouseExited

    private void openBraketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBraketMouseEntered
      this.openBraket.setBackground(Color.green);  // TODO add your handling code here:
    }//GEN-LAST:event_openBraketMouseEntered

    private void openBraketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBraketMouseExited
       this.openBraket.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_openBraketMouseExited

    private void closeBraketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBraketMouseEntered
       this.closeBraket.setBackground(Color.green);
    }//GEN-LAST:event_closeBraketMouseEntered

    private void closeBraketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBraketMouseExited
      this.closeBraket.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_closeBraketMouseExited

    private void tanButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanButtonMouseEntered
     this.tanButton.setBackground(Color.green);
    }//GEN-LAST:event_tanButtonMouseEntered

    private void tanButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanButtonMouseExited
        this.tanButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_tanButtonMouseExited

    private void logButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseEntered
          this.logButton.setBackground(Color.green);
    }//GEN-LAST:event_logButtonMouseEntered

    private void logButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseExited
       this.logButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_logButtonMouseExited

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
     Enabled() ;
     
    }//GEN-LAST:event_onButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
       Disabled() ;
    }//GEN-LAST:event_offButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Scientific().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeBraket;
    private javax.swing.JButton comaButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel keypadPanel;
    private javax.swing.JButton logButton;
    private javax.swing.JTextField mainScreen;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JRadioButton offButton;
    private javax.swing.JRadioButton onButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton openBraket;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JButton pieButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JPanel scientificPanel;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

    private void Enabled() {
        mainScreen.setBackground(Color.LIGHT_GRAY);
        mainScreen.setText("");
        mainScreen.setEnabled(true);
        oneButton.setEnabled(true);
        twoButton.setEnabled(true);
        threeButton.setEnabled(true);
        fourButton.setEnabled(true);
         fiveButton.setEnabled(true);
          sixButton.setEnabled(true);
           sevenButton.setEnabled(true);
            eightButton.setEnabled(true);
             nineButton.setEnabled(true);
              zeroButton.setEnabled(true);
               comaButton.setEnabled(true);
                plusButton.setEnabled(true);
                 minusButton.setEnabled(true);
                 divideButton.setEnabled(true);
                  multiplyButton.setEnabled(true);
                  pieButton.setEnabled(true);
                  equalButton.setEnabled(true);
                  cancelButton.setEnabled(true);
                  deleteButton.setEnabled(true);
                  sinButton.setEnabled(true);
                  tanButton.setEnabled(true);
                   logButton.setEnabled(true);
                    closeBraket.setEnabled(true);
                    openBraket.setEnabled(true);
                  cosButton.setEnabled(true);
                  offButton.setEnabled(true);
                  onButton.setEnabled(false);
                  
           }

    private void Disabled() {
       // mainScreen.setVisible(false);
        mainScreen.setBackground(Color.black);
       mainScreen.setEditable(false);
       oneButton.setEnabled(false);
        twoButton.setEnabled(false);
        threeButton.setEnabled(false);
        fourButton.setEnabled(false);
         fiveButton.setEnabled(false);
          sixButton.setEnabled(false);
           sevenButton.setEnabled(false);
            eightButton.setEnabled(false);
             nineButton.setEnabled(false);
              zeroButton.setEnabled(false);
               comaButton.setEnabled(false);
                plusButton.setEnabled(false);
                divideButton.setEnabled(false);
                 minusButton.setEnabled(false);
                  multiplyButton.setEnabled(false);
                    pieButton.setEnabled(false);
                  equalButton.setEnabled(false);
                  cancelButton.setEnabled(false);
                  deleteButton.setEnabled(false);
                  sinButton.setEnabled(false);
                  cosButton.setEnabled(false);
                   tanButton.setEnabled(false);
                   logButton.setEnabled(false);
                    closeBraket.setEnabled(false);
                    openBraket.setEnabled(false);
                  offButton.setEnabled(true);
                  onButton.setEnabled(true);
    }
}
